# Generated by Django 5.2.17 on 2026-09-07 15:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="County",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Counties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "Facilities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FormDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=150)),
                ("short_name", models.CharField(max_length=30)),
                ("category", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHMT", "County Health Management Team"),
                            ("SCHMT", "Sub-County Health Management Team"),
                            ("FACILITY_INCHARGE", "Facility In-charge"),
                            ("MEL_LEAD", "MEL Lead"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "can_upload",
                    models.BooleanField(
                        default=False,
                        help_text="Allowed to upload MOH 748 (and future form) workbooks.",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.county",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="MOH748Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=20)),
                ("source_filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("facility_rows_parsed", models.PositiveIntegerField(default=0)),
                ("record_rows_created", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moh748_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SubCounty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_counties",
                        to="core.county",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sub-counties",
                "ordering": ["county__name", "name"],
                "unique_together": {("county", "name")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="sub_county",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.subcounty",
            ),
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "sub_county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wards",
                        to="core.subcounty",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wards",
                "ordering": ["sub_county__county__name", "sub_county__name", "name"],
                "unique_together": {("sub_county", "name")},
            },
        ),
        migrations.AddField(
            model_name="facility",
            name="ward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="facilities",
                to="core.ward",
            ),
        ),
        migrations.CreateModel(
            name="MOH748Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=20)),
                (
                    "commodity",
                    models.CharField(
                        choices=[
                            ("LLINS", "LLINs"),
                            ("AL_6", "AL 6s"),
                            ("AL_12", "AL 12s"),
                            ("AL_18", "AL 18s"),
                            ("AL_24", "AL 24s"),
                        ],
                        max_length=10,
                    ),
                ),
                ("beginning_balance", models.IntegerField(blank=True, null=True)),
                ("days_out_of_stock", models.IntegerField(blank=True, null=True)),
                ("losses_excl_expiries", models.IntegerField(blank=True, null=True)),
                ("near_expiry_6mo", models.IntegerField(blank=True, null=True)),
                ("negative_adjustments", models.IntegerField(blank=True, null=True)),
                ("physical_count", models.IntegerField(blank=True, null=True)),
                ("positive_adjustments", models.IntegerField(blank=True, null=True)),
                ("quantity_received", models.IntegerField(blank=True, null=True)),
                (
                    "quantity_requested_resupply",
                    models.IntegerField(blank=True, null=True),
                ),
                ("quantity_expired", models.IntegerField(blank=True, null=True)),
                ("total_dispensed", models.IntegerField(blank=True, null=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moh748_records",
                        to="core.facility",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="core.moh748upload",
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "facility__name", "commodity"],
                "unique_together": {("facility", "period", "commodity", "upload")},
            },
        ),
        migrations.CreateModel(
            name="Threshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_key", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=150)),
                ("unit", models.CharField(blank=True, max_length=30)),
                ("green_max", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amber_max", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "is_draft",
                    models.BooleanField(
                        default=True,
                        help_text="Draft threshold — set from an assumption, not yet confirmed by MOH.",
                    ),
                ),
                ("definition", models.TextField(blank=True)),
                (
                    "form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thresholds",
                        to="core.formdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["form__display_order", "metric_key"],
                "unique_together": {("form", "metric_key")},
            },
        ),
        migrations.CreateModel(
            name="IndicatorSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=20)),
                ("indicator_key", models.CharField(max_length=100)),
                ("indicator_label", models.CharField(max_length=150)),
                ("metric_key", models.CharField(max_length=100)),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GREEN", "Green"),
                            ("AMBER", "Amber"),
                            ("RED", "Red"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.county",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_summaries",
                        to="core.facility",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_summaries",
                        to="core.formdefinition",
                    ),
                ),
                (
                    "sub_county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.subcounty",
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.ward",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Indicator summaries",
                "ordering": ["-period", "facility__name"],
                "unique_together": {
                    ("form", "facility", "period", "indicator_key", "metric_key")
                },
            },
        ),
        migrations.AlterUniqueTogether(
            name="facility",
            unique_together={("ward", "name")},
        ),
    ]
