# Generated by Django 5.2.17 on 2026-09-10 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CHPCommodityUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        help_text="Reporting month this upload covers, e.g. 2026-08.",
                        max_length=20,
                    ),
                ),
                ("source_filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("area_rows_parsed", models.PositiveIntegerField(default=0)),
                ("record_rows_created", models.PositiveIntegerField(default=0)),
                (
                    "unresolved_geography_rows",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Rows kept under an 'Unresolved' bucket because eCHIS couldn't resolve their CHU/area.",
                    ),
                ),
                (
                    "unmapped_chw_rows",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Rows for a CHP area with no currently active CHW mapped to it.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chp_commodity_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityHealthUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which facility this CHU reports through. Left blank until a CHU-to-facility mapping is supplied.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_health_units",
                        to="core.facility",
                    ),
                ),
                (
                    "sub_county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="community_health_units",
                        to="core.subcounty",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Community health units",
                "ordering": ["sub_county__county__name", "sub_county__name", "name"],
                "unique_together": {("sub_county", "name")},
            },
        ),
        migrations.CreateModel(
            name="CHPArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("chw_count", models.PositiveIntegerField(blank=True, null=True)),
                ("chw_name", models.CharField(blank=True, max_length=255)),
                ("chw_username", models.CharField(blank=True, max_length=255)),
                ("chw_contact_id", models.CharField(blank=True, max_length=255)),
                ("chw_mapping_status", models.CharField(blank=True, max_length=100)),
                ("geography_status", models.CharField(blank=True, max_length=100)),
                (
                    "county",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chp_areas",
                        to="core.county",
                    ),
                ),
                (
                    "community_health_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chp_areas",
                        to="core.communityhealthunit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CHP areas",
                "ordering": ["county__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="CHPCommodityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=20)),
                (
                    "commodity",
                    models.CharField(
                        choices=[
                            ("act_6", "AL 6s"),
                            ("act_12", "AL 12s"),
                            ("act_18", "AL 18s"),
                            ("act_24", "AL 24s"),
                            ("rdts", "RDTs (Malaria Test Kit)"),
                            ("dt_250", "Amoxicillin 250mg DT"),
                            ("ors_zinc", "Zinc / ORS Co-Pack"),
                            ("ors_sachets", "ORS Sachets"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "beginning_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "quantity_received",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "quantity_dispensed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "positive_adjustments",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "negative_adjustments",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "ending_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("latest_balance_date", models.DateField(blank=True, null=True)),
                (
                    "consumption_log_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("latest_consumption_date", models.DateField(blank=True, null=True)),
                (
                    "supply_form_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "physical_count",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "count_form_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("latest_count_date", models.DateField(blank=True, null=True)),
                (
                    "stock_on_hand",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "weeks_of_stock",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "stock_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Stockout", "Stockout"),
                            ("Low stock", "Low stock"),
                            ("Adequate", "Adequate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "stockout_form_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("latest_stockout_date", models.DateField(blank=True, null=True)),
                (
                    "service_qty_review_flag",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "chp_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commodity_records",
                        to="core.chparea",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="core.chpcommodityupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "chp_area__name", "commodity"],
                "unique_together": {("chp_area", "period", "commodity", "upload")},
            },
        ),
    ]
