# Generated by Django 5.2.17 on 2026-09-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_chpcommodityupload_communityhealthunit_chparea_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chpcommodityrecord",
            name="commodity",
            field=models.CharField(
                choices=[
                    ("act_6", "AL 6s"),
                    ("act_12", "AL 12s"),
                    ("act_18", "AL 18s"),
                    ("act_24", "AL 24s"),
                    ("rdts", "RDTs (Malaria Test Kit)"),
                    ("dt_250", "Amoxicillin 250mg DT"),
                    ("ors_zinc", "Zinc / ORS Co-Pack"),
                    ("ors_sachets", "ORS Sachets"),
                    ("zinc", "Zinc Sulphate 20mg Tablets"),
                    ("pcm", "Paracetamol (PCM)"),
                    ("glucometer_strips", "Glucometer Strips"),
                    ("gloves", "Gloves"),
                    ("dispensing_envelopes", "Medical Dispensing Envelopes"),
                ],
                max_length=20,
            ),
        ),
    ]
